beta_settings:
  cloud_sql_instances: andersen-lab:us-central1:cendr

runtime: custom
service: default
env: flex
entrypoint: gunicorn -b :$PORT main:app --ssl-version TLSv1_2
runtime_config:
  python_version: 3

api_version: 1
threadsafe: true
skip_files:
  - ^(.*/)?.*vcf\.gz$
  - ^(.*/)?.*vcf$
  - ^(.*/)?.*gff3\.gz$
  - ^(.*/)?.*gff3$  
  - ^(.*/)?.*bed\.gz$
  - ^(.*/)?.*bed$
  - ^\.git/.*$
  - ^.*pyc$  
  - ^scripts/.*$
  - ^tests/.*$

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 20

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 60
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 120
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300