runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT main:app
runtime_config:
  python_version: 2

api_version: 1
threadsafe: true
skip_files:
  - ^(.*/)?.*vcf\.gz$
  - ^(.*/)?.*vcf$
  - ^(.*/)?.*gff3\.gz$
  - ^(.*/)?.*gff3$  
  - ^(.*/)?.*bed\.gz$
  - ^(.*/)?.*bed$
  - ^\.git/.*$
  - ^.*pyc$  
  - ^scripts/.*$
  - ^tests/.*$


resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10


automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5

# Handlers define how to route requests to your application.
handlers:
- url: /cronmapping
  script: run.app 
  login: admin

- url: .*
  script: run.app  # a WSGI application in the main module's global scope

