runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT main:app
runtime_config:
  python_version: 3

api_version: 1
threadsafe: true
skip_files:
  - ^(.*/)?.*vcf\.gz$
  - ^(.*/)?.*vcf$
  - ^(.*/)?.*gff3\.gz$
  - ^(.*/)?.*gff3$  
  - ^(.*/)?.*bed\.gz$
  - ^(.*/)?.*bed$
  - ^\.git/.*$
  - ^.*pyc$  
  - ^scripts/.*$
  - ^tests/.*$

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6

resources:
  cpu: .5
  memory_gb: 0.5
  disk_size_gb: 10

# Handlers define how to route requests to your application.
handlers:
- url: /cronmapping
  script: run.app 
  login: admin

- url: .*
  script: run.app  # a WSGI application in the main module's global scope

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300