{% set version = '1.0.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cegwas
  version: {{ version|replace("-", "_") }}

source:

  git_url: http://www.github.com/andersenlab/cegwas
  git_tag: v1.0.2

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-doparallel
    - r-iterators
    - r-tidyverse
    - r-data.table
    - r-foreach
    - r-ggmap
    - r-regress
    - r-sp
    - r-rrblup=4.6.1
    - bcftools>=1.2

  run:
    - r-base
    - r-doparallel
    - r-iterators
    - r-tidyverse
    - r-data.table
    - r-foreach
    - r-ggmap
    - r-regress
    - r-sp
    - r-rrblup=4.6.1
    - bcftools>=1.2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('cegwas')"           # [not win]
    - "\"%R%\" -e \"library('cegwas')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.github.com/andersenlab/cegwas
  license: GPL
  summary: Functions to process data, perform GWA mappings, identify confidence intervals, and
    genes with variants within the confidence interval.
  license_family: GPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: cegwas
# Title: A set of functions to process phenotype data, perform GWAS, and perform post-mapping data processing for C. elegans.
# Version: 1.0
# Authors@R: person("Stefan", "Zdraljevic", email = "stefanzdraljevic2018@u.northwestern.edu", role = c("aut", "cre"))
# Description: Functions to process data, perform GWA mappings, identify confidence intervals, and genes with variants within the confidence interval.
# Depends: R (>= 3.2.0)
# Imports: doParallel, iterators, parallel, reshape2, foreach, stringr, tidyr, data.table, ggplot2, dplyr
# License: GPL
# LazyData: true

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
